#!/bin/bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║        ⚠️  THIS REPOSITORY HAS MOVED ⚠️                    ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "⛔ This installer will NOT work correctly!"
echo ""
echo "This project has been migrated to Codeberg and requires"
echo "files from the new repository to install properly."
echo ""
echo "📍 New location:"
echo "   https://codeberg.org/justaguylinux/butterbash"
echo ""
echo "To install butterbash correctly:"
echo ""
echo "   1. Clone the new repository:"
echo "      git clone https://codeberg.org/justaguylinux/butterbash"
echo ""
echo "   2. Run the installer from there:"
echo "      cd butterbash"
echo "      ./install.sh"
echo ""
echo "All future updates happen at the new location."
echo ""
exit 1
